# Generated by Django 3.2.9 on 2021-11-24 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('address', models.TextField()),
                ('author_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name="Author's Email")),
                ('author_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('short_desc', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('book_id', models.CharField(max_length=220, unique=True)),
                ('on_board', models.BooleanField(default=True)),
                ('read_time_mins', models.IntegerField(blank=True, null=True)),
                ('on_board_timestamp', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.author')),
            ],
        ),
    ]
