# Generated by Django 3.2.9 on 2021-11-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_bookproxy_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='active_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Activated'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(blank=True, max_length=220, null=True, unique=True),
        ),
    ]
