# Generated by Django 3.2.9 on 2021-11-25 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_series_is_active'),
        ('books', '0005_auto_20211125_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='series.series'),
        ),
    ]
