# Generated by Django 3.2.9 on 2021-11-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
