# Generated by Django 3.2.9 on 2021-11-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0005_tag_created'),
        ('books', '0007_book_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='book_tags', to='genres.Tag'),
        ),
    ]
