# Generated by Django 3.2.9 on 2021-11-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0005_tag_created'),
        ('books', '0009_book_is_borrowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='book_tags', to='genres.Tag'),
        ),
    ]
