# Generated by Django 3.2.9 on 2021-11-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='has_book',
            field=models.BooleanField(default=False),
        ),
    ]
