# Generated by Django 3.2.9 on 2021-11-25 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='timestamp',
            new_name='active_timestamp',
        ),
    ]
