# Generated by Django 3.2.9 on 2021-11-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_rename_timestamp_genre_active_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='active_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
