# Generated by Django 3.2.9 on 2021-11-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0003_alter_genre_active_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
