# Generated by Django 3.2.9 on 2021-11-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_alter_borroweditem_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borroweditem',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
