# Generated by Django 3.2.9 on 2021-11-26 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0004_auto_20211127_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borroweditem',
            old_name='book_returend_date',
            new_name='book_returned_date',
        ),
    ]
