# Generated by Django 3.2.9 on 2021-11-27 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_has_book'),
        ('borrow', '0005_rename_book_returend_date_borroweditem_book_returned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borroweditem',
            name='borrow_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.useraccount'),
        ),
    ]
