# Generated by Django 3.2.9 on 2021-11-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Series', 'verbose_name_plural': 'All Series'},
        ),
        migrations.AddField(
            model_name='series',
            name='series_id',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
