# Generated by Django 3.2.9 on 2021-11-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_auto_20211125_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
